# Generated by Django 2.0.7 on 2018-07-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Status',
            new_name='StatusBoolean',
        ),
    ]
